In [73]:
print("hello world")
#hello can you see this new change
#please write your name just to make sure we can all edit this
#bea
#dilara
#test

hello world


In [74]:
#Imports
import numpy as np
import scipy as sci

In [84]:
"""
Class for quantum register for n number of qubits
"""
def tensor_Product(a,b):
    product= np.tensordot(a,b, axes=0)
    return product

class Quantum_Register:
    def __init__(self,n):
        self.n=n
        self.psi=np.zeros((2,)*n)       # make array of zeros with right shape
        self.psi[(0,)*n]=1              # put psi[0,0,...,0] to 1
        

        

In [ ]:
"""
Hadamard Gate Single - Qubit Operator
"""

H_matrix=1/np.sqrt(2)*np.array([[1, 1],
                                [1,-1]])

In [85]:
"""
Class for the quantum circuits 
"""
class Quantum_Circuit:
    def __init__(self):
        self = self

In [86]:
"""Testing block """

qubit0= np.array([1,0])

qubit1= np.array([0,1])
qubit3= (1/np.sqrt(2))*(qubit0 + qubit1)


newRegister= Quantum_Register(4)

print(newRegister.n)
print(newRegister.psi)

#print(tensor_Product(qubit3,qubit3))

4
[[[[1. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
